export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS';

export const MOVIELIST_REQUEST = 'MOVIELIST_REQUEST';
export const MOVIELIST_SUCCESS = 'MOVIELIST_SUCCESS';
export const MOVIELIST_FAILED = 'MOVIELIST_FAILED';

export const WATCHMOVIE_REQUEST = 'WATCHMOVIE_REQUEST';
export const WATCHMOVIE_SUCCESS = 'WATCHMOVIE_SUCCESS';
export const WATCHMOVIE_FAILED = 'WATCHMOVIE_FAILED';
